[devel] Add import capacities

diff --git a/src/lib/core-cluster b/src/lib/core-cluster
--- a/src/lib/core-cluster
+++ b/src/lib/core-cluster
@@ -407,6 +407,51 @@ function doClusterConfigurationCreate {
     fi
 }
 
+
+
+# import cluster configuration
+function doClusterConfigurationImport {
+    local cn=$1
+    rm -rf /tmp/sxcm-repo  &> /dev/null
+    echo -e "\e[1m\e[34mStart\e[0m import process for cluster \e[1m$cn\e[0m"
+    if [[ "$cn" == "" ]]; then
+        echo -en "Cluster name [$cn] : "
+        read cn
+    fi
+    if [[ $cn == '' ]]; then
+        cn="myClusterName"
+    fi
+    local CLUSTER_CONFDIR=$SXCM_USER_CONF_DIR/$SXCM_USER_CONF_DIR_CLUSTER/$cn
+    local SXCM_GIT_BRANCH=$cn
+    if [[ -d $CLUSTER_CONFDIR ]]; then
+        echo -e "  Cluster \e[1m$cn\e[0m \e[31mis already managed\e[0m. Could not import \e[1m$cn\e[0m"
+        exit;
+    else
+        echo -e "  Cluster \e[1m$cn\e[0m \e[32mis not managed\e[0m"
+    fi
+    git clone $SXCM_GIT_REPO /tmp/sxcm-repo
+    if [[ $? -gt 0 ]]; then
+        echo -e "  Repository \e[1m$SXCM_GIT_REPO\e[0m \e[31mis not clonable\e[0m. Could not import \e[1m$cn\e[0m"
+        exit;
+    else
+        echo -e "  Repository \e[1m$SXCM_GIT_REPO\e[0m \e[32mis cloned\e[0m"
+    fi
+    cd /tmp/sxcm-repo  &> /dev/null
+    git checkout $SXCM_GIT_BRANCH  &> /dev/null
+    if [[ $? -gt 0 ]]; then
+        echo -e "  Cluster state \e[1m$SXCM_GIT_BRANCH\e[0m \e[31mdoesn't exist\e[0m. Could not import \e[1m$cn\e[0m"
+        exit;
+    else
+        echo -e "  Cluster state \e[1m$SXCM_GIT_BRANCH\e[0m \e[32mis cloned\e[0m"
+    fi
+    mv /tmp/sxcm-repo $SXCM_USER_CONF_DIR/$SXCM_USER_CONF_DIR_CLUSTER/$cn &> /dev/null
+    echo -e "  Cluster \e[1m$cn\e[0m is \e[32mimported\e[0m from \e[1m$SXCM_GIT_BRANCH\e[0m cluster state "
+    cd -  &> /dev/null
+    rm -rf /tmp/sxcm-repo  &> /dev/null
+    setActiveCluster $cn
+    echo -e "  \e[1m\e[32mSet active\e[0m cluster set to \e[1m$cn\e[0m"
+}
+
 # info on cluster configuration
 function doClusterConfigurationInfo {
     local cn=${1}
@@ -443,14 +488,16 @@ function doClusterConfigurationInfo {
         else
             STATE="\e[34mdefined\e[0m"
         fi
-        printf "\e[1m%-8s\e[0m %s\n" name $cn
-        printf "\e[1m%-8s\e[0m %s\n" profile $PROFILE
-        printf "\e[1m%-8s\e[0m %s$STATE\n" state ""
-        printf "\e[1m%-8s\e[0m%s\n" desc "$desc"
-        printf "\e[1m%-8s\e[0m%s\n" services "$service"
-        printf "\e[1m%-8s\e[0m%s\n" cost " $hourlyCost €/h"
-        printf "\e[1m%-8s\e[0m %s\n" "adm user" "kubeadmin"
-        printf "\e[1m%-8s\e[0m %s\n" "adm pwd" "$admpwd"
+        printf "\e[1m%-10s\e[0m %s\n" name $cn
+        printf "\e[1m%-10s\e[0m %s\n" profile $PROFILE
+        printf "\e[1m%-10s\e[0m %s$STATE\n" state ""
+        printf "\e[1m%-10s\e[0m%s\n" desc "$desc"
+        printf "\e[1m%-10s\e[0m%s\n" services "$service"
+        printf "\e[1m%-10s\e[0m%s\n" cost " $hourlyCost €/h"
+        printf "\e[1m%-10s\e[0m %s\n" "git repo" "$SXCM_GIT_REPO"
+        printf "\e[1m%-10s\e[0m %s\n" "git branch" "$SXCM_GIT_BRANCH"
+        printf "\e[1m%-10s\e[0m %s\n" "adm user" "kubeadmin"
+        printf "\e[1m%-10s\e[0m %s\n" "adm pwd" "$admpwd"
         exit 0;
     else
         echo -e "Cluster configuration named \e[1m$cn\e[0m in $clusterConfDir doesn't exist"
@@ -823,6 +870,29 @@ EOF
     fi
 }
 
+# sub-menu for import command
+function menuClusterImport {
+    if [[ -z "$1" || "$1" == "" ]]; then
+        menuHeadArt
+            cat <<EOF
+
+sxcm import sub-command for importing a sxcm managed cluster
+
+This sub-command helps you add an existing cluster configuration to the managed cluster stack
+
+Usage:
+sxcm import NAME
+
+Examples:
+# Import the cluster named myClusterName using the cluster git repository
+sxcm import myClusterName
+
+EOF
+    else
+        doClusterConfigurationImport $1 $2
+    fi
+}
+
 # sub-menu for info command
 function menuClusterInfo {
     if [[ -z "$1" || "$1" == "" ]]; then
@@ -908,6 +978,7 @@ function menuClusterConnect {
 # main menu for the cluster sub-command
 function menuCluster {
     case $1 in
+        import)         menuClusterImport ${2};;
         create)         menuClusterCreate ${2} ${3};;
         info)           menuClusterInfo ${2};;
         edit)           menuClusterEdit ${2};;
